title: Austin Ellefson's CyberSecurity Portolio
description: I have actively documented and completed a range of cybersecurity projects to enhance my skills and knowledge in the field. These projects showcase my ability to tackle real-world challenges and implement effective solutions. Below are a few key projects I’ve worked on:
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
